server:
  port: 8081

spring:
  application:
    name: fraud-stream-producer
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: "false"

producer:
  topic: transactions
  rate: 100
  csv-path: ../sample-data/transactions.csv
